(ns scicloj.clay.v2.old.quarto.highlight-styles)

;; All the [Quarto code highlight styles](https://quarto.org/docs/output-formats/html-code.html):
(def a11y :a11y)
(def arrow :arrow)
(def atom-one :atom-one)
(def ayu :ayu)
(def breeze :breeze)
(def github :github)
(def gruvbox :gruvbox)
(def pygments :pygments)
(def tango :tango)
(def espresso :espresso)
(def zenburn :zenburn)
(def kate :kate)
(def monochrome :monochrome)
(def breezedark :breezedark)
(def haddock :haddock)
(def dracula :dracula)
(def monokai :monokai)
(def nord :nord)
(def oblivion :oblivion)
(def printing :printing)
(def radical :radical)
(def solarized :solarized)
(def vim-dark :vim-dark)
