(ns scicloj.clay.v2.old.quarto.themes)

;; All the [Quarto themes](https://quarto.org/docs/output-formats/html-themes.html):
(def default :default)
(def cerulean :cerulean)
(def cosmo :cosmo)
(def cyborg :cyborg)
(def darkly :darkly)
(def flatly :flatly)
(def journal :journal)
(def litera :litera)
(def lumen :lumen)
(def lux :lux)
(def materia :materia)
(def minty :minty)
(def morph :morph)
(def pulse :pulse)
(def quartz :quartz)
(def sandstone :sandstone)
(def simplex :simplex)
(def sketchy :sketchy)
(def slate :slate)
(def solar :solar)
(def spacelab :spacelab)
(def superhero :superhero)
(def united :united)
(def vapor :vapor)
(def yeti :yeti)
(def zephyr :zephyr)
